In [1]:
import pandas as pd

In [4]:
faq=pd.read_csv("../data/faq.csv")
products=pd.read_csv("../data/products.csv")
print('faq shape',faq.shape)
print('product shape',products.shape)

faq shape (10, 2)
product shape (20, 10)

In [5]:
faq.head()

,question,answer
0,What is your return policy?,You can return eligible products within 30 day...
1,Can I exchange a product?,"Yes, eligible products can be exchanged for an..."
2,How long does shipping take?,Standard delivery usually takes 3 to 5 busines...
3,Do you offer free shipping?,Free standard shipping is available on orders ...
4,Can I cancel my order?,Orders can be cancelled before they are shippe...

In [6]:
products.head()

,product_id,name,category,description,price,color,size,material,occasion,style
0,P001,Classic White Cotton Shirt,Shirt,Classic regular-fit cotton shirt suitable for ...,1299,White,S|M|L|XL,Cotton,Casual|College,Minimal
1,P002,Black Oversized Hoodie,Hoodie,Comfortable oversized hoodie with a relaxed fi...,1799,Black,S|M|L|XL,Cotton Blend,Casual|College,Streetwear
2,P003,Blue Straight Fit Jeans,Jeans,Classic blue straight-fit jeans suitable for e...,1899,Blue,28|30|32|34|36,Cotton Denim,Casual|College,Classic
3,P004,Beige Wide Leg Trousers,Trousers,Relaxed wide-leg trousers that work well for s...,1699,Beige,S|M|L|XL,Polyester Blend,Casual|Office,Smart Casual
4,P005,Floral Summer Dress,Dress,Lightweight floral dress designed for warm wea...,1999,Floral,S|M|L|XL,Rayon,Summer|Vacation,Feminine

In [7]:
faq.isnull().sum()

question    0
answer      0
dtype: int64

In [8]:
products.isnull().sum()

product_id     0
name           0
category       0
description    0
price          0
color          0
size           0
material       0
occasion       0
style          0
dtype: int64